all:
  children:
    web:
      hosts:
        frontend1:
          ansible_host: 40.172.101.56
        frontend2:
          ansible_host: 40.172.228.30
    backend:
      hosts:
        backend1:
          ansible_host: 51.112.229.70
        backend2:
          ansible_host: 3.29.81.22

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/nayab-key.pem
    ansible_python_interpreter: /usr/bin/python3
