---
- name: Deploy Customer PHP Content
  hosts: tag_Role_web
  become: yes
  tasks:
    - name: Copy Customer 1 Index
      copy:
        src: ../../websites/customer1/index.php
        dest: /var/www/customer1/index.php
        owner: www-data

    - name: Copy Customer 2 Index
      copy:
        src: ../../websites/customer2/index.php
        dest: /var/www/customer2/index.php
        owner: www-data
