plugin: amazon.aws.aws_ec2
regions:
  - me-central-1
groups:
  backend: "'backend' in tags.Name"
  frontend: "'frontend' in tags.Name"
  web: "'backend' in tags.Name"
keyed_groups:
  - key: tags.Name
    separator: ""
    prefix: ""
hostnames:
  - public_ip_address
compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
